name: tic_tac_toe
description: A command-line TicTacToe game
version: 1.0.0
repository: https://github.com/YacineSteeve/tic_tac_toe

environment:
  sdk: ^3.4.3

dev_dependencies:
  lints: ^3.0.0
dependencies:
  args: ^2.5.0
